<div class="controls">
<?= $this->tabs ?>
<?php

$rows = $this->table->fetchData();

if (empty($rows)) {
    $maxId = null;
} else {
    $maxId = current($rows)->id;
}

$filter = $this->filterEditor->getFilter();

?>
<h1>SNMP Traps</h1>
<?php if ($maxId && ! $filter->isEmpty()): ?>
<span class="action-links">
<?= $this->qlink(
    $this->translate('Acknowledge'),
    $this->url()->with('action', 'ack')->with('maxId', $maxId),
    null,
    array(
        'class' => 'icon-ok',
        'title' => $this->translate('Acknowledge all traps in the shown list')
    ))
?><?= $this->qlink(
    $this->translate('Un-acknowledge'),
    $this->url()->with('action', 'unack')->with('maxId', $maxId),
    null,
    array(
        'class' => 'icon-rewind',
        'title' => $this->translate('Remove acknowledgements from all traps in the shown list')
    ))
?></span>
<?php endif ?>
<?= $this->filterEditor ?><br />
<?= $this->table->getPaginator() ?>

<!--

 | listener_id | timestamp           | host_name | src_address | src_port | dst_address | dst_port | auth   | message | sys_uptime | type | version | requestid  | transactionid | messageid  | oid                      | short_name       | mib_name           | transport | security | v3_sec_level | v3_sec_name | v3_sec_engine | v3_ctx_name | v3_ctx_engine    

-->
</div>
<div class="content" data-base-target="_next">
<?= $this->table->render() ?>
</div>
