<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($trap->getOidName($trap->oid)) ?></h1>
<?php if ($trap->message): ?>
<p><?= $this->escape($trap->message) ?></p>
<?php endif ?>
<?php
/*
if ($trap->resolvesOid($trap->oid)) {
    $trapOid = $trap->resolveOid($trap->oid);
    if ($trapOid->description && $trapOid->description !== $trap->message) {
        printf("<p>%s</p>\n", $this->escape($trapOid->description));
    }
}
*/

?>
</div>
<!--<pre>
<?= $this->escape(print_r($this->trap, 1)) ?>
</pre>-->
<div class="content">
<table class="key-value-table table-x-rows-collapsible">
<tr><th>Timestamp</th><td><?= $trap->timestamp ?></td></tr>
<tr><th>Hostname</th><td><?= $this->escape($trap->host_name) ?></td></tr>
<tr><th>OID</th><td><?= $trap->oid ?> (<?= $trap->type ?>)</td></tr>
<tr><th>Sender</th><td><?= $trap->transport ?>://<?= $trap->src_address ?>:<?= $trap->src_port ?>, SNMP <?= $trap->version ?></td></tr>
<tr><th>Auth</th><td><?= $trap->auth ?></td></tr>
<?php foreach ($this->trap->varbinds as $var): ?>
<?php if ($var->value === '') continue; ?>
<tr>
  <th><?php
if ($trap->resolvesOid($var->oid)) {
    echo $this->escape($trap->resolveOid($var->oid)->short_name);
} else {
    echo $this->escape($var->oid);
}
 ?></th>
  <td><span class="collapse-handle"><?php

if ($var->type === 'object_id') {
    if ($trap->resolvesOid($var->value)) {
        echo $this->escape($trap->getOidName($var->value));
    } else {
        echo $this->escape($var->value);
    }
} elseif (preg_match('~^https?://~', $var->value)) {
    echo $this->qlink($var->value, $var->value);
} else {
    echo $this->escape($var->value);
}

?>
</span><div class="collapsible">
<p>
<?php if ($trap->resolvesOid($var->oid)): ?>
<?php
    $res = $trap->resolveOid($var->oid);
?>
<?= $this->escape($res->description) ?></p>
<pre>
MIB : <?= $this->escape($res->mib_name) ?> 
Name: <?= $this->escape($res->short_name) ?> 
<?php else: ?>
<?= $this->escape($var->oid) ?></p>
<pre>
<?php endif ?>
OID : <?= $this->escape($var->oid) ?> 
Type: <?= $var->type ?>
</pre>
</div></td>
</tr>
<?php endforeach ?>
</table>
</div>
